const packageJson = require('./package.json')

/**
 * Public beta installers, built without paid signing certificates.
 *
 * Same identity as a release ("Unoblox", app id io.dsh.desktop, userData
 * `dsh-desktop`), so a later signed release installs over a beta and keeps its
 * data. What differs:
 *
 * - macOS is ad-hoc signed (`identity: '-'`). Building rewrites the app after
 *   Electron's own signature, so an unsigned bundle carries a broken seal that
 *   Gatekeeper reports as "damaged" on Apple Silicon. An ad-hoc seal is valid,
 *   so macOS shows its ordinary "cannot verify" prompt, which the user allows
 *   once under Privacy & Security. Hardened runtime is off: it exists for
 *   notarization, and its library validation needs a Team ID an ad-hoc
 *   signature does not have.
 * - The disk image shows how to allow that first open (dmg-background*.png,
 *   generated by scripts/generate-brand-assets.mjs).
 * - Windows is unsigned; SmartScreen asks once (More info, Run anyway).
 * - Nothing is published, and the installers carry no update feed.
 */
// Shared with the background generator, which draws the targets under these.
const DMG_WINDOW = require('./build/brand/dmg-layout.json')

module.exports = {
  ...packageJson.build,
  directories: {
    ...packageJson.build.directories,
    output: 'dist-beta'
  },
  artifactName: 'Unoblox-Beta-${version}-${os}-${arch}.${ext}',
  mac: {
    ...packageJson.build.mac,
    // The zip exists for auto-update, which the beta does not have.
    target: ['dmg'],
    identity: '-',
    hardenedRuntime: false
  },
  linux: {
    ...packageJson.build.linux,
    // The .deb installs electron-builder's AppArmor profile and sets up the
    // chrome-sandbox helper, which Ubuntu 24.04+ needs for Chromium's
    // sandbox; the AppImage cannot. Both ship.
    target: [
      { target: 'AppImage', arch: ['x64'] },
      { target: 'deb', arch: ['x64'] }
    ],
    maintainer: 'Unoblox <hello@unoblox.ai>',
    vendor: 'Unoblox'
  },
  deb: {
    // apt shows this name; the repository package name is dsh-desktop.
    packageName: 'unoblox',
    artifactName: 'Unoblox-Beta-${version}-linux-${arch}.${ext}'
  },
  dmg: {
    ...packageJson.build.dmg,
    title: 'Unoblox Beta',
    background: 'build/dmg-background.png',
    iconSize: 96,
    window: { width: DMG_WINDOW.width, height: DMG_WINDOW.height },
    contents: [
      { x: DMG_WINDOW.app.x, y: DMG_WINDOW.app.y, type: 'file' },
      { x: DMG_WINDOW.applications.x, y: DMG_WINDOW.applications.y, type: 'link', path: '/Applications' }
    ]
  },
  nsis: {
    ...packageJson.build.nsis,
    artifactName: 'Unoblox-Beta-${version}-windows-${arch}-setup.${ext}'
  },
  publish: null
}
