const packageJson = require('./package.json')

/**
 * Public beta installers, built without paid signing certificates.
 *
 * Same identity as a release ("unoblox works", app id ai.unoblox.works, userData
 * `dsh-desktop`), so a later signed release installs over a beta and keeps its
 * data. What differs:
 *
 * - macOS is ad-hoc signed (`identity: '-'`). Building rewrites the app after
 *   Electron's own signature, so an unsigned bundle carries a broken seal that
 *   Gatekeeper reports as "damaged" on Apple Silicon. An ad-hoc seal is valid,
 *   so macOS shows its ordinary "cannot verify" prompt, which the user allows
 *   once under Privacy & Security. Hardened runtime is off: it exists for
 *   notarization, and its library validation needs a Team ID an ad-hoc
 *   signature does not have.
 * - The disk image shows how to allow that first open (dmg-background*.png,
 *   generated by scripts/generate-brand-assets.mjs).
 * - Windows is unsigned; SmartScreen asks once (More info, Run anyway).
 * - Nothing is published, and the installers carry no update feed.
 */
// Shared with the background generator, which draws the targets under these.
const DMG_WINDOW = require('./build/brand/dmg-layout.json')

/*
 * Real signing switches on when CI provides the secrets (see
 * docs/code-signing.md); without them the build stays as described above.
 * - macOS: CSC_LINK (Developer ID Application .p12) signs with hardened
 *   runtime; APPLE_API_KEY (+ _ID, _ISSUER) notarizes and staples the app.
 * - Windows: SSL.com eSigner (ESIGNER_*) through a sign hook, or Azure
 *   Artifact Signing (AZURE_* plus the account settings below).
 */
const MAC_SIGNED = Boolean(process.env.CSC_LINK)
const MAC_NOTARIZED = MAC_SIGNED && Boolean(process.env.APPLE_API_KEY && process.env.APPLE_API_KEY_ID && process.env.APPLE_API_ISSUER)
const ESIGNER = Boolean(process.env.ESIGNER_USERNAME && process.env.ESIGNER_PASSWORD && process.env.ESIGNER_CREDENTIAL_ID && process.env.ESIGNER_TOTP_SECRET)
const AZURE = !ESIGNER && Boolean(process.env.AZURE_TENANT_ID && process.env.AZURE_CLIENT_ID && process.env.AZURE_CLIENT_SECRET &&
  process.env.AZURE_SIGNING_ENDPOINT && process.env.AZURE_SIGNING_ACCOUNT && process.env.AZURE_SIGNING_PROFILE)

function windowsSigning() {
  if (ESIGNER) {
    return { signtoolOptions: { ...packageJson.build.win.signtoolOptions, sign: './scripts/esigner-windows-hook.mjs' } }
  }
  if (AZURE) {
    return {
      signtoolOptions: null,
      azureSignOptions: {
        // Must match the certificate's subject: the legal entity, not the brand.
        publisherName: process.env.AZURE_SIGNING_PUBLISHER || 'OGMA CONSULTING PRIVATE LIMITED',
        endpoint: process.env.AZURE_SIGNING_ENDPOINT,
        codeSigningAccountName: process.env.AZURE_SIGNING_ACCOUNT,
        certificateProfileName: process.env.AZURE_SIGNING_PROFILE
      }
    }
  }
  return {}
}

module.exports = {
  ...packageJson.build,
  directories: {
    ...packageJson.build.directories,
    output: 'dist-beta'
  },
  artifactName: 'unoblox-works-beta-${version}-${os}-${arch}.${ext}',
  mac: {
    ...packageJson.build.mac,
    // The dmg is for people; the zip is what over-the-air updates download
    // (src/main/update/ota-install.ts unpacks it with ditto).
    target: ['dmg', 'zip'],
    ...(MAC_SIGNED
      ? { hardenedRuntime: true, notarize: MAC_NOTARIZED }
      : { identity: '-', hardenedRuntime: false })
  },
  win: {
    ...packageJson.build.win,
    ...windowsSigning()
  },
  linux: {
    ...packageJson.build.linux,
    // The .deb installs electron-builder's AppArmor profile and sets up the
    // chrome-sandbox helper, which Ubuntu 24.04+ needs for Chromium's
    // sandbox; the AppImage cannot. Both ship.
    target: [
      { target: 'AppImage', arch: ['x64'] },
      { target: 'deb', arch: ['x64'] }
    ],
    maintainer: 'unoblox <hello@unoblox.ai>',
    vendor: 'unoblox'
  },
  deb: {
    // apt shows this name; the repository package name is dsh-desktop.
    packageName: 'unoblox-works',
    // The first .deb betas were named "unoblox"; installing this one removes it.
    fpm: ['--conflicts', 'unoblox', '--replaces', 'unoblox'],
    artifactName: 'unoblox-works-beta-${version}-linux-${arch}.${ext}'
  },
  dmg: {
    ...packageJson.build.dmg,
    title: 'unoblox works beta',
    // A notarized app opens without the first-open steps the beta panel explains.
    background: MAC_NOTARIZED ? 'build/dmg-background-signed.png' : 'build/dmg-background.png',
    iconSize: 96,
    window: { width: DMG_WINDOW.width, height: DMG_WINDOW.height },
    contents: [
      { x: DMG_WINDOW.app.x, y: DMG_WINDOW.app.y, type: 'file' },
      { x: DMG_WINDOW.applications.x, y: DMG_WINDOW.applications.y, type: 'link', path: '/Applications' }
    ]
  },
  nsis: {
    ...packageJson.build.nsis,
    artifactName: 'unoblox-works-beta-${version}-windows-${arch}-setup.${ext}'
  },
  publish: null
}
